### ISSUE TITLE
New Product Type for Chartering

### ISSUE THREAD

**Issue by Sdfraga** [Sdfraga/VSP_TR0009#11]
Create a new Product Type for Chartering.

**Comment by AnaFigueiredoMSC** [comment]
Product Type 56C - MSC Chartering created.

You can start to use this for our program.

**Comment by Sdfraga** [comment]
When we use product type 56C we have an error for the variant "NO_BERTLING":

Message Code: FTR_GUI
Message Number: 327
Message Text: Correct the interest form

**Technical Info: Changes in branch issue11-new-product-type**

**Comment by AnaFigueiredoMSC** [comment]
Transaction 1000000000000 created in D710 with no issue using FTR_CREATE.

Product Type 56C
Company code 2200

Please check.

**Comment by Sdfraga** [comment]
Still some issues.
Execute variant **"Issue#11 - New Product Type for Charter"** on FM  BAPI_FTR_FAC_DEALCREATE and check the RETURN table with the errors

**Comment by AnaFigueiredoMSC** [comment]
Issue solved: missing customizing for 56C under TRM -> Transaction Manager -> General Settings -> Accounting -> Settings for Position Management -> Assign Posistion Management Procedure

**Comment by Sdfraga** [comment]
Contract **1000000000002** for company code **2200** created with program **/MSC/VSP_CHARTERING_CONTRACTS**
