### ISSUE TITLE
BP Derived Flow Concurrency

### ISSUE THREAD

**Issue by Sdfraga** [Sdfraga/VSP_TR0009#16]
Issue #5 is implemented.

The code is not checking if we override the BP Derived Flow.
When the BP entered in the chartering contract already has a derived flow, what should we do?

1 - We don't care and we override the new derived flow
2 - A popup should appear asking for user confirmation (how to manage the migration process with this option?)
3 - Contract must be cancelled

**Comment by AnaFigueiredoMSC** [comment]
For me, we could think on both options - 1 and 2. 
But this can be checked with the business to understand if it makes sense -> is it possible to have more than one contract active for a BP at the same time?
IF yes, and if we found a contract with same BP and different Derived Flows, check if the contract is still open:
- if YES, raise a pop-up for the user to confirm the correct Flow 
- if NO overwrite the Derived Flows with the new ones

During the migration phase I don't expect to have duplicate cases, taking into consideration that each BP is a vessel and also analyzing the excel provided, there are no duplicate BPs.
But if it happens, it depends on the tool, if a program will be created the same behavior should be affected , for the case of a YES, this related contract should be canceled and proceed to the next one.
The ones in error can be processed manually (where the pop-up will be raised).

**Comment by Sdfraga** [comment]
This is stand by since we decided to treat MSC Commission Percentage as a charge in the contract

**Comment by Sdfraga** [comment]
Derived Flows will not be used anymore. Sorry @AnastasiaMSC  :)
