### ISSUE TITLE
Custom FTR Tab

### ISSUE THREAD

**Issue by Sdfraga** [Sdfraga/VSP_TR0009#18]
Custom Contractual Data tab must be added to the new transaction type 56C - Chartering.
Ask Rui Malta to also include this new Transaction Type to the tab control flow.

Suggestion: We should have a customizing table where we could enable/disable the custom tab by Transaction Type

**Comment by AnastasiaMSC** [comment]
Ana, please, fill free to request the custo table with CC, product type and the check box activate in the incident -> 2000029032

Thank you!

**Comment by Sdfraga** [comment]
@AnaFigueiredoMSC is working on this with Rui Malta.
https://blogs.sap.com/2014/07/22/how-to-manage-the-status-of-custom-fields-in-trm/

**Comment by Sdfraga** [comment]
Done!
