### ISSUE TITLE
BP assign to more than one contract?

### ISSUE THREAD

**Issue by AnaFigueiredoMSC** [Sdfraga/VSP_TR0009#19]
For Chartering, is it possible in a business view, to have more than one contract active for a BP at the same time?

**Comment by Sdfraga** [comment]
We can have different contracts for the same BP (vessel), for example if we charter Anastasia (vessel) and we then we lease it.

Based on this, we will use different derived flows transaction types.

- 100 Assigned 
- 200 Obtained

New field needed in the screen to get the derived flow transaction type. Should be created in the Execution options.
