### ISSUE TITLE
Customizable Charges

### ISSUE THREAD

**Issue by Sdfraga** [Sdfraga/VSP_TR0009#3]
In the contract we can have several charges:
First Day Payment
Last Day Payment 
MSC Percentage 
MSC Lump Sum
Broker Percentage
Broker Lump Sum

Analyse the strategy to be used in order to create these charges.
Separate class for charges?

**Comment by Sdfraga** [comment]
Customizing Table - /MSC/VSP_CHA_FLW

**Comment by Sdfraga** [comment]
**First Day Payment (FDP)** - _Additional flow_ in the contract - Contract Creation Action
**Last Day Payment (LDP)** - _Additional flow_ in the contract - Contract Closing Action
**MSC Commission Percentage (MCP)** - Managed with Business Partner _Derived Flows_ (#5 #16)
**MSC Commission Lump/Sum (MCL)** - Very few contracts with this option. Are you still going for it @AnastasiaMSC ?
**Broker Commission Percentage (BCP)** - Charge in the Contract
**Broker Commission Lump/Sum (BCL** - Charge in the Contract

The following information is needed in order to create the Additional Flows & Charges:

Additional Flows (FDP & LDP)
- Flow Type
- Flow Direction
- Assignment 

Contract Charges (BCP & BCL)
- Condition Type

Should we create customizing tables or we hardcode this in the program for now but be prepared for flexibility in the future?

**Additional Question:** 
Will we have dedicated Flow Types for FDP and LDP and dedicated condition for (BCP and BCL)?

**Comment by Sdfraga** [comment]
Think about customizing cluster for separate Flows and Charges customizing

**Comment by Sdfraga** [comment]
New Customizig Cluster: /MSC/CHARTERING

**Comment by AnastasiaMSC** [comment]
MSC Commission Lump/Sum (MCL) - Very few contracts with this option. Are you still going for it @AnastasiaMSC ? - We got the confirmation, that we need it from the last discussion with Thierry.

**Comment by Sdfraga** [comment]
@AnaFigueiredoMSC will customize /MSC/VSP_TR0009 in SM34 with all the possible entries.
DHC (Daily Hire Charge) - done
FDP - done
LDP - todo
MCP - todo
MCL - todo
BCP - done
BCL - done

**Comment by Sdfraga** [comment]
All done but there is bug when Daily Hire( MCP and MCL correspondingly) is chosen with Monthly Frequency due to mismatch between Contract Charges Frequency Data Element

**Comment by Sdfraga** [comment]
Done

**Comment by Sdfraga** [comment]
Missing Customizing for Additional Flows related with First Day Payment and Last Day Payment:
MCP First Day
MCP Last DAy
MCL First Day
MCL Last Day
BCP First Day
BCP Last Day

**Comment by Sdfraga** [comment]
New Chartering Flows created and added to customizing cluster for customizing:

- **DHCF** - Daily Hire Commission - First Day Payment
- **DHCL** - Daily Hire Commission - Last Day Payment
- **MICF** - MSC Interest Rate Commission - First Day Payment
- **MICL** - MSC Interest Rate Commission - Last Day Payment
- **MLCF** - MSC Lump Sum Commission - First Day Payment
- **MLCL** - MSC Lump Sum Commission - Last Day Payment
- **BICF** - Broker Interest Rate Commission - First Day Payment
- **BICL** - Broker Interest Rate Commission - Last Day Payment
- **BLCF** - Broker Lump Sum Commission - First Day Payment
- **BLCL** - Broker Lump Sum Commission - Last Day Payment

**Comment by Sdfraga** [comment]
Done!
