### ISSUE TITLE
Will we need a Prolongation option? 

### ISSUE THREAD

**Issue by Sdfraga** [Sdfraga/VSP_TR0009#8]
When working with Instrument Rate the option was there but for facilities it seems there is no prolongation option...

**Comment by AnastasiaMSC** [comment]
Yes, we need the Prolongation option, because some contracts, which we will migrate, they can be already a prolongation for some other contract. Thnx.

**Comment by AnastasiaMSC** [comment]
we need to write to Rui Malta to extend the IFRS16 Contractual data from 55A and 54A to 56A.

**Comment by Sdfraga** [comment]
OK.
We need to understand how to manage this prolongation option and the necessary tasks to be done for development

**Comment by Sdfraga** [comment]
Question Closed
Follow to #9
